-- Sales Log database setup + inventory upgrade.
-- Safe to run again in Supabase -> SQL Editor.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  slot integer not null check (slot between 1 and 5),
  name text not null,
  price numeric(12,2) not null default 0,
  deal_type text not null default 'none' check (deal_type in ('none','bundle','free')),
  deal_qty integer not null default 0,
  deal_price numeric(12,2) not null default 0,
  free_qty integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(user_id, slot)
);

-- Inventory/product-type fields added by v3.
alter table public.products add column if not exists product_type text not null default 'standard';
alter table public.products add column if not exists stock numeric(12,3) not null default 0;
alter table public.products add column if not exists standard_amount numeric(12,3) not null default 1;
alter table public.products add column if not exists full_price numeric(12,2) not null default 0;

create table if not exists public.sales (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sold_at timestamptz not null default now(),
  total numeric(12,2) not null default 0,
  note text not null default '',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.sales enable row level security;

drop policy if exists "products_select_own" on public.products;
drop policy if exists "products_insert_own" on public.products;
drop policy if exists "products_update_own" on public.products;
drop policy if exists "products_delete_own" on public.products;
create policy "products_select_own" on public.products for select using (auth.uid() = user_id);
create policy "products_insert_own" on public.products for insert with check (auth.uid() = user_id);
create policy "products_update_own" on public.products for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "products_delete_own" on public.products for delete using (auth.uid() = user_id);

drop policy if exists "sales_select_own" on public.sales;
drop policy if exists "sales_insert_own" on public.sales;
drop policy if exists "sales_update_own" on public.sales;
drop policy if exists "sales_delete_own" on public.sales;
create policy "sales_select_own" on public.sales for select using (auth.uid() = user_id);
create policy "sales_insert_own" on public.sales for insert with check (auth.uid() = user_id);
create policy "sales_update_own" on public.sales for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "sales_delete_own" on public.sales for delete using (auth.uid() = user_id);

-- Record a sale and deduct fractional inventory in one database transaction.
create or replace function public.record_sale_with_stock(
  p_sale_id uuid,
  p_sold_at timestamptz,
  p_total numeric,
  p_note text,
  p_items jsonb
) returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  item jsonb;
  v_slot integer;
  v_used numeric;
begin
  for item in select value from jsonb_array_elements(p_items)
  loop
    v_slot := coalesce((item->>'id')::integer, 0);
    v_used := coalesce((item->>'stockUsed')::numeric, 0);

    if v_used > 0 then
      update public.products
      set stock = stock - v_used,
          updated_at = now()
      where user_id = auth.uid()
        and slot = v_slot
        and stock >= v_used;

      if not found then
        raise exception 'Insufficient stock for product slot %', v_slot;
      end if;
    end if;
  end loop;

  insert into public.sales(id,user_id,sold_at,total,note,items)
  values(p_sale_id,auth.uid(),p_sold_at,p_total,coalesce(p_note,''),p_items);
end;
$$;

-- Deleting a sale restores the exact stock amount that sale consumed.
create or replace function public.delete_sale_restore_stock(p_sale_id uuid)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  sale_items jsonb;
  item jsonb;
  v_slot integer;
  v_used numeric;
begin
  select items into sale_items
  from public.sales
  where id = p_sale_id and user_id = auth.uid()
  for update;

  if sale_items is null then
    raise exception 'Sale not found';
  end if;

  for item in select value from jsonb_array_elements(sale_items)
  loop
    v_slot := coalesce((item->>'id')::integer, 0);
    v_used := coalesce((item->>'stockUsed')::numeric, 0);
    if v_used > 0 then
      update public.products
      set stock = stock + v_used,
          updated_at = now()
      where user_id = auth.uid() and slot = v_slot;
    end if;
  end loop;

  delete from public.sales where id = p_sale_id and user_id = auth.uid();
end;
$$;

grant execute on function public.record_sale_with_stock(uuid,timestamptz,numeric,text,jsonb) to authenticated;
grant execute on function public.delete_sale_restore_stock(uuid) to authenticated;

-- Realtime support for live updates between phones.
do $$ begin
  alter publication supabase_realtime add table public.products;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.sales;
exception when duplicate_object then null; end $$;
