-- Run this entire file once in Supabase -> SQL Editor.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  slot integer not null check (slot between 1 and 5),
  name text not null,
  price numeric(12,2) not null default 0,
  deal_type text not null default 'none' check (deal_type in ('none','bundle','free')),
  deal_qty integer not null default 0,
  deal_price numeric(12,2) not null default 0,
  free_qty integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(user_id, slot)
);

create table if not exists public.sales (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sold_at timestamptz not null default now(),
  total numeric(12,2) not null default 0,
  note text not null default '',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.sales enable row level security;

drop policy if exists "products_select_own" on public.products;
drop policy if exists "products_insert_own" on public.products;
drop policy if exists "products_update_own" on public.products;
drop policy if exists "products_delete_own" on public.products;
create policy "products_select_own" on public.products for select using (auth.uid() = user_id);
create policy "products_insert_own" on public.products for insert with check (auth.uid() = user_id);
create policy "products_update_own" on public.products for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "products_delete_own" on public.products for delete using (auth.uid() = user_id);

drop policy if exists "sales_select_own" on public.sales;
drop policy if exists "sales_insert_own" on public.sales;
drop policy if exists "sales_update_own" on public.sales;
drop policy if exists "sales_delete_own" on public.sales;
create policy "sales_select_own" on public.sales for select using (auth.uid() = user_id);
create policy "sales_insert_own" on public.sales for insert with check (auth.uid() = user_id);
create policy "sales_update_own" on public.sales for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "sales_delete_own" on public.sales for delete using (auth.uid() = user_id);

-- Realtime support for live updates between phones.
do $$ begin
  alter publication supabase_realtime add table public.products;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.sales;
exception when duplicate_object then null; end $$;
