-- Sales Log v5.0 — MULTI-DRIVER ADMIN
-- Run this entire file in Supabase -> SQL Editor.
-- IMPORTANT: change the email below if your admin email changes.

create table if not exists public.admin_emails (
  email text primary key
);

insert into public.admin_emails(email)
values ('jonathan.gaming1112@gmail.com')
on conflict (email) do nothing;

alter table public.admin_emails enable row level security;
revoke all on public.admin_emails from anon, authenticated;

create or replace function public.is_sales_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.admin_emails a
    where lower(a.email)=lower(coalesce(auth.jwt()->>'email',''))
  );
$$;
grant execute on function public.is_sales_admin() to authenticated;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  display_name text not null default '',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
drop policy if exists "profiles_read_own" on public.profiles;
create policy "profiles_read_own" on public.profiles for select using (auth.uid()=user_id);

create or replace function public.handle_new_sales_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.profiles(user_id,email,display_name)
  values(new.id,coalesce(new.email,''),coalesce(new.raw_user_meta_data->>'display_name',''))
  on conflict(user_id) do update set email=excluded.email;
  return new;
end;
$$;

drop trigger if exists sales_user_profile_created on auth.users;
create trigger sales_user_profile_created
after insert or update of email on auth.users
for each row execute function public.handle_new_sales_user();

insert into public.profiles(user_id,email)
select id,coalesce(email,'') from auth.users
on conflict(user_id) do update set email=excluded.email;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  slot integer not null check (slot between 1 and 5),
  name text not null,
  price numeric(12,2) not null default 0,
  deal_type text not null default 'none',
  deal_qty integer not null default 0,
  deal_price numeric(12,2) not null default 0,
  free_qty integer not null default 0,
  product_type text not null default 'standard',
  stock numeric(12,3) not null default 0,
  standard_amount numeric(12,3) not null default 1,
  full_price numeric(12,2) not null default 0,
  updated_at timestamptz not null default now(),
  unique(user_id,slot)
);

create table if not exists public.sales (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sold_at timestamptz not null default now(),
  total numeric(12,2) not null default 0,
  note text not null default '',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.sales add column if not exists supplement_amount numeric(12,2) not null default 0;
alter table public.sales add column if not exists supplement_note text not null default '';
alter table public.sales add column if not exists supplement_status text not null default 'none';
alter table public.sales add column if not exists supplement_reviewed_at timestamptz;
alter table public.sales add column if not exists supplement_reviewed_by uuid references auth.users(id);

alter table public.products enable row level security;
alter table public.sales enable row level security;

drop policy if exists "products_select_own" on public.products;
drop policy if exists "products_insert_own" on public.products;
drop policy if exists "products_update_own" on public.products;
drop policy if exists "products_delete_own" on public.products;
create policy "products_select_own" on public.products for select using (auth.uid()=user_id);
create policy "products_insert_own" on public.products for insert with check (auth.uid()=user_id);
create policy "products_update_own" on public.products for update using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "sales_select_own" on public.sales;
drop policy if exists "sales_insert_own" on public.sales;
drop policy if exists "sales_update_own" on public.sales;
drop policy if exists "sales_delete_own" on public.sales;
create policy "sales_select_own" on public.sales for select using (auth.uid()=user_id);
create policy "sales_insert_own" on public.sales for insert with check (auth.uid()=user_id);

-- Driver sale: stock is deducted only from the signed-in driver's own inventory.
create or replace function public.record_sale_with_stock(
  p_sale_id uuid,
  p_sold_at timestamptz,
  p_total numeric,
  p_note text,
  p_items jsonb,
  p_supplement_amount numeric default 0,
  p_supplement_note text default ''
) returns void
language plpgsql
security invoker
set search_path=public
as $$
declare
  item jsonb;
  v_slot integer;
  v_used numeric;
  v_supp numeric := greatest(coalesce(p_supplement_amount,0),0);
begin
  if v_supp > 0 and length(trim(coalesce(p_supplement_note,'')))=0 then
    raise exception 'Supplement reason is required';
  end if;

  for item in select value from jsonb_array_elements(p_items)
  loop
    v_slot:=coalesce((item->>'id')::integer,0);
    v_used:=coalesce((item->>'stockUsed')::numeric,0);
    if v_used>0 then
      update public.products
      set stock=stock-v_used, updated_at=now()
      where user_id=auth.uid() and slot=v_slot and stock>=v_used;
      if not found then raise exception 'Insufficient stock for product slot %',v_slot; end if;
    end if;
  end loop;

  insert into public.sales(
    id,user_id,sold_at,total,note,items,
    supplement_amount,supplement_note,supplement_status
  ) values(
    p_sale_id,auth.uid(),p_sold_at,p_total,coalesce(p_note,''),p_items,
    v_supp,coalesce(p_supplement_note,''),
    case when v_supp>0 then 'pending' else 'none' end
  );
end;
$$;
grant execute on function public.record_sale_with_stock(uuid,timestamptz,numeric,text,jsonb,numeric,text) to authenticated;

create or replace function public.get_my_sales()
returns setof public.sales
language sql
stable
security definer
set search_path=public
as $$
  select * from public.sales where user_id=auth.uid() order by sold_at desc;
$$;
grant execute on function public.get_my_sales() to authenticated;

-- Admin: list every non-admin account as a driver.
create or replace function public.admin_list_drivers()
returns table(user_id uuid,email text,display_name text)
language sql
stable
security definer
set search_path=public
as $$
  select p.user_id,p.email,p.display_name
  from public.profiles p
  where public.is_sales_admin()
    and not exists(select 1 from public.admin_emails a where lower(a.email)=lower(p.email))
  order by coalesce(nullif(p.display_name,''),p.email);
$$;
grant execute on function public.admin_list_drivers() to authenticated;

create or replace function public.admin_get_driver_products(p_driver_id uuid)
returns setof public.products
language sql
stable
security definer
set search_path=public
as $$
  select * from public.products
  where public.is_sales_admin() and user_id=p_driver_id
  order by slot;
$$;
grant execute on function public.admin_get_driver_products(uuid) to authenticated;

create or replace function public.admin_get_driver_sales(p_driver_id uuid)
returns setof public.sales
language sql
stable
security definer
set search_path=public
as $$
  select * from public.sales
  where public.is_sales_admin() and user_id=p_driver_id
  order by sold_at desc;
$$;
grant execute on function public.admin_get_driver_sales(uuid) to authenticated;

-- Admin: set the selected driver's five stock values.
create or replace function public.admin_set_driver_stock(
  p_driver_id uuid,
  p_stock jsonb,
  p_reason text
) returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  i integer;
  v_stock numeric;
  names text[] := array['Large product','Ketnet','3Motion','NEP','Median'];
  prices numeric[] := array[50,15,15,15,35];
  types text[] := array['fractional_large','standard','standard','standard','standard'];
begin
  if not public.is_sales_admin() then raise exception 'Admin access required'; end if;
  if length(trim(coalesce(p_reason,'')))=0 then raise exception 'Adjustment reason is required'; end if;
  if not exists(select 1 from public.profiles where user_id=p_driver_id) then raise exception 'Driver not found'; end if;

  for i in 1..5 loop
    v_stock:=greatest(coalesce((p_stock->>i::text)::numeric,0),0);
    insert into public.products(
      user_id,slot,name,price,product_type,stock,standard_amount,full_price,
      deal_type,deal_qty,deal_price,free_qty,updated_at
    ) values(
      p_driver_id,i,names[i],prices[i],types[i],v_stock,
      case when i=1 then 0.7 else 1 end,
      case when i=1 then 60 else 0 end,
      'none',0,0,0,now()
    )
    on conflict(user_id,slot) do update set
      name=excluded.name, price=excluded.price, product_type=excluded.product_type,
      stock=excluded.stock, standard_amount=excluded.standard_amount,
      full_price=excluded.full_price, updated_at=now();
  end loop;
end;
$$;
grant execute on function public.admin_set_driver_stock(uuid,jsonb,text) to authenticated;

-- Admin: approve/decline one extra-pay request for the selected driver.
create or replace function public.admin_review_supplement(
  p_driver_id uuid,
  p_sale_id uuid,
  p_status text
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.is_sales_admin() then raise exception 'Admin access required'; end if;
  if p_status not in ('approved','declined') then raise exception 'Invalid status'; end if;

  update public.sales
  set supplement_status=p_status,
      supplement_reviewed_at=now(),
      supplement_reviewed_by=auth.uid()
  where id=p_sale_id
    and user_id=p_driver_id
    and supplement_amount>0
    and supplement_status='pending';

  if not found then raise exception 'Pending supplement request not found'; end if;
end;
$$;
grant execute on function public.admin_review_supplement(uuid,uuid,text) to authenticated;

-- Driver app users cannot delete sales or restore stock.
revoke delete on public.sales from authenticated;

-- Realtime.
do $$ begin
  alter publication supabase_realtime add table public.products;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.sales;
exception when duplicate_object then null; end $$;
